# Generated by Django 4.2.2 on 2023-07-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service_rest", "0004_remove_appointment_date_time_appointment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="vin",
            field=models.CharField(max_length=17),
        ),
    ]
